version: 0.2
phases:
  pre-build:
    commands:
    - echo "Enetered the pre-build phase"
  build:
    commands:
    - echo "Enetered the build phase"
    - mvn clean prepare-package war:explode
  post-build:
    commands: 
    - echo "Enetered the post build phase"
    - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*